# Generated by Django 2.2.6 on 2024-01-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240117_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
